### ISSUE TITLE
Make SVG bigger on mobile

### ISSUE THREAD

**Issue by menthy-wu** [citrushack/cutiehack2023#113]
<img width="299" alt="image" src="https://github.com/citrushack/cutiehack2023/assets/73259022/ac9aa271-f532-499b-a825-5775082c0db3">

**Comment by JohnZ9865** [comment]
This appears on website upon getting on. When I click into Volunteer, it shows the second error.
![image](https://github.com/citrushack/cutiehack2023/assets/64669569/b9757376-4f3f-4e78-a793-ff6143eb57c0)

![image](https://github.com/citrushack/cutiehack2023/assets/64669569/709200c7-e7aa-403a-b67c-b354dbd8041f)
